# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '54Days' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rosary
	pod 'SwiftyJSON'
	pod 'JTAppleCalendar', '~> 6.0'
	pod 'RealmSwift'
end
